# Generated by Django 3.0.4 on 2021-05-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UsuarioLogin', models.CharField(max_length=30)),
                ('UsuarioNombre', models.CharField(max_length=30)),
                ('UsuarioApellido', models.CharField(max_length=30)),
                ('UsuarioEmail', models.CharField(max_length=30)),
                ('UsuarioGrupo', models.CharField(max_length=30)),
                ('UsuarioPwd', models.CharField(max_length=30)),
                ('UsuarioRePwd', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id'],
            },
        ),
    ]
