# Generated by Django 3.0.4 on 2021-05-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdministracion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
