# Generated by Django 3.0.4 on 2021-06-09 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('breed', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cat',
                'verbose_name_plural': 'Cats',
            },
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppForTesting.Cat')),
            ],
            options={
                'verbose_name': 'Feeding',
                'verbose_name_plural': 'Feedings',
            },
        ),
    ]
